<h2 style = "color : Brown"> Creating NumPy Arrays </h2 >



 The following ways are commonly used when you know the size of the array beforehand:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.random.random()```: Create array of random numbers
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [8]:
import numpy as np


##### Tip: Use help to see the syntax when required

##### Creating a 1 D array of ones

In [10]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

##### Notice that, by default, numpy creates data type = float64



In [11]:
arr.dtype

dtype('float64')

##### Can provide dtype explicitly using dtype


In [14]:
arr = np.ones(5, dtype=int)
arr


array([1, 1, 1, 1, 1])

In [15]:
arr.dtype

dtype('int64')

##### Creating a 5  x 3 array of ones


In [33]:
np.ones((5,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

##### Creating array of zeros

In [34]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [25]:
# convert the type into integer.
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [32]:
# Create a list of integers range between 1 to 5.
np.array(list(range(1,15,2)))

array([ 1,  3,  5,  7,  9, 11, 13])

In [44]:
np.arange(4)

array([0, 1, 2, 3])

In [45]:
np.arange(3.0)

array([0., 1., 2.])

##### Notice that 3 is included, 35 is not, as in standard python lists

From 3 to 35 with a step of 2

In [48]:
np.arange(0,35,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34])

##### Array of random numbers 


In [102]:
np.random.randint(3, size=10)

array([2, 1, 0, 2, 1, 2, 0, 0, 1, 0])

In [60]:
np.random.randint(3,5, size=10)

array([4, 3, 4, 3, 3, 4, 3, 4, 4, 3])

##### 2D Array of random numbers 


In [81]:

np.random.random([1,2])

array([[0.15691577, 0.41699828]])

###### Sometimes, you know the length of the array, not the step size

Array of length 20 between 1 and 10

In [72]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

<h2 style = "color : Sky blue"> Exercises </h2>



Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
-  `np.random.randint()`: Create a random array of integers within a particular range

In [79]:
np.full([5,6],50)

array([[50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50]])

In [83]:
np.tile([1,2,3],3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [84]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [98]:
n=5
arr=np.ones([5,5],dtype=int)

In [99]:
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [100]:
arr[1:-1,1:-1]=0

In [101]:
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])